<Project Sdk="Microsoft.NET.Sdk">
  <!--
    SDK, publicize, ILRepack, deploy, and version increment are via Directory.Build.props/targets.
  -->

  <PropertyGroup>
    <AssemblyName>ControlledFiltering</AssemblyName>
    <RootNamespace>ControlledFiltering</RootNamespace>
  </PropertyGroup>

</Project>
