name: 🐛 Bug Report
description: Report a bug or issue with one of the mods
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: dropdown
    id: mod
    attributes:
      label: Which mod is this bug related to?
      description: Select the mod that has the bug
      options:
        - Morning Exercise
        - Copy Materials Tool
        - Empty Storage
        - Longer Arms
        - Debug Fog of War
        - Bonbon Tree Boost
        - Threshold Fixed
        - Other / Multiple
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: If applicable, paste relevant log output or error messages here
      placeholder: Paste logs here (use code blocks with ```)
      render: shell

  - type: markdown
    attributes:
      value: |
        ## Player.log File
        
        Please provide your `player.log` file, which contains important debugging information. You can find it at:
        
        **Windows:**
        ```
        %USERPROFILE%\AppData\LocalLow\Klei\Oxygen Not Included\player.log
        ```
        Or navigate to: `C:\Users\[YourUsername]\AppData\LocalLow\Klei\Oxygen Not Included\player.log`
        
        **macOS:**
        ```
        ~/Library/Logs/Unity/Player.log
        ```
        
        **Linux:**
        ```
        ~/.config/unity3d/Klei/Oxygen Not Included/Player.log
        ```
        
        **Note:** The log file can be large. Please either:
        - Attach the file directly to this issue (drag and drop), or
        - Paste the relevant sections in the field below (especially any error messages or stack traces)

  - type: textarea
    id: player_log
    attributes:
      label: Player.log Contents
      description: Paste relevant sections from your player.log file here, or mention that you've attached the file above
      placeholder: |
        Paste relevant log sections here, especially any errors, exceptions, or stack traces related to the bug.
        
        If the file is too large, please attach it directly to this issue instead.
      render: shell

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Game crash, save corruption, etc.)
        - High (Major functionality broken)
        - Medium (Minor functionality broken)
        - Low (Cosmetic issue, minor inconvenience)
      default: 2
    validations:
      required: true

  - type: input
    id: game_version
    attributes:
      label: Game Version
      description: What version of Oxygen Not Included are you running?
      placeholder: e.g., Build 700386, DLC version, etc.
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      description: What version of the mod are you using?
      placeholder: e.g., 0.1.8, 0.1.86, etc.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to make sure this hasn't been reported already
          required: true
        - label: I have included all relevant information
          required: true
        - label: I have tested with the latest version of the mod
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the bug
      placeholder: Add any other context about the problem here...

