<Project Sdk="Microsoft.NET.Sdk">
  <!--
    SDK, publicize, ILRepack, deploy, and version increment are via Directory.Build.props/targets.
  -->

  <PropertyGroup>
    <AssemblyName>ControlledMods</AssemblyName>
    <RootNamespace>ControlledMods</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiserableUtils\MiserableUtils.csproj" />
  </ItemGroup>

</Project>
