<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>BlankProjectSteamTest</AssemblyName>
    <RootNamespace>BlankProjectSteamTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="preview.jpg" CopyToOutputDirectory="PreserveNewest" Condition="Exists('$(MSBuildProjectDirectory)\preview.jpg')" />
  </ItemGroup>

</Project>
